//GLScopeMac.java
//GUI For Oscilloscope Functions


//Based on (GPL) Java OpenGL examples from
//http://plugins.netbeans.org/PluginPortal/faces/PluginDetailPage.jsp?pluginid=3260


//This program is free software; you can redistribute it and/or
//modify it under the terms of the GNU General Public License as
//published by the Free Software Foundation; either version 3 of the
//License, or (at your option) any later version.
//
//This program is distributed in the hope that it will be useful, but
//WITHOUT ANY WARRANTY; without even the implied warranty of
//MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
//General Public License for more details:
//http://www.gnu.org/licenses/gpl.txt

//Copyright 2009 Brian Satzinger


package scopeduino.display;

import java.awt.Font;
import java.util.*;

import com.sun.opengl.util.Animator;
import java.awt.Dimension;
import java.awt.EventQueue;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseMotionAdapter;
import java.awt.event.MouseWheelEvent;
import java.awt.event.MouseWheelListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.media.opengl.GLCanvas;
import javax.media.opengl.GLCapabilities;
import javax.swing.AbstractListModel;
import javax.swing.BorderFactory;
import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JPanel;
import javax.swing.JPopupMenu;
import javax.swing.JScrollPane;
import javax.swing.JSlider;
import javax.swing.JTabbedPane;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.UIManager;
import javax.swing.WindowConstants;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import serial.LogicDAQ;



/**
 *
 * @author cylab
 * @author mbien
 */
public class GLScopeMac extends JFrame {

    static {
        // When using a GLCanvas, we have to set the Popup-Menues to be HeavyWeight,
        // so they display properly on top of the GLCanvas
        JPopupMenu.setDefaultLightWeightPopupEnabled(false);
    }
    
    private Animator animator;
    GLRenderer rend;
    Refresher r;

    int oldx = -1;
    int oldy = -1;

    /** Creates new form MainFrame */
    public GLScopeMac() {
        initComponents();

      
        setTitle("Scopeduino");

        rend = new GLRenderer();

        canvas.addGLEventListener(rend);
        animator = new Animator(canvas);




        // This is a workaround for the GLCanvas not adjusting its size, when the frame is resized.
        canvas.setMinimumSize(new Dimension());         
        
        this.addWindowListener(new WindowAdapter() {

            @Override
            public void windowClosing(WindowEvent e) {
                // Run this on another thread than the AWT event queue to
                // make sure the call to Animator.stop() completes before
                // exiting
                new Thread(new Runnable() {

                    public void run() {
                        animator.stop();
                        System.exit(0);
                    }
                }).start();
            }
        });
    }

    @Override
    public void setVisible(boolean show){
        if(!show)
            animator.stop();
        super.setVisible(show);
        if(!show)
            animator.start();

        
        r = new Refresher(canvas);
        r.start();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new JPanel();
        canvas = new GLCanvas(createGLCapabilites());
        jSlider6 = new JSlider();
        jPanel1 = new JPanel();
        jTabbedPane1 = new JTabbedPane();
        ConnectionPanel = new JPanel();
        btnDetectSerial = new JButton();
        scrlSerialPorts = new JScrollPane();
        lstSerialPorts = new JList();
        btnConnect = new JButton();
        DisplayPanel = new JPanel();
        jLabel2 = new JLabel();
        sldBackground = new JSlider();
        chkPause = new JCheckBox();
        jLabel1 = new JLabel();
        sldZoom = new JSlider();
        jLabel3 = new JLabel();
        sldPan = new JSlider();
        CursorPanel = new JPanel();
        chkCursors = new JCheckBox();
        jLabel4 = new JLabel();
        sldHC1 = new JSlider();
        sldHC2 = new JSlider();
        jLabel5 = new JLabel();
        lblt1 = new JLabel();
        lblt2 = new JLabel();
        lbldt = new JLabel();
        lblF = new JLabel();

        GroupLayout jPanel4Layout = new GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        addWindowListener(new WindowAdapter() {
            public void windowOpened(WindowEvent evt) {
                formWindowOpened(evt);
            }
            public void windowActivated(WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        canvas.addMouseWheelListener(new MouseWheelListener() {
            public void mouseWheelMoved(MouseWheelEvent evt) {
                canvasMouseWheelMoved(evt);
            }
        });
        canvas.addMouseListener(new MouseAdapter() {
            public void mouseReleased(MouseEvent evt) {
                canvasMouseReleased(evt);
            }
        });
        canvas.addMouseMotionListener(new MouseMotionAdapter() {
            public void mouseDragged(MouseEvent evt) {
                canvasMouseDragged(evt);
            }
        });

        GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        btnDetectSerial.setLabel("Detect Serial Ports");
        btnDetectSerial.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt) {
                btnDetectSerialMouseClicked(evt);
            }
        });
        btnDetectSerial.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btnDetectSerialActionPerformed(evt);
            }
        });

        lstSerialPorts.setModel(new AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        scrlSerialPorts.setViewportView(lstSerialPorts);

        btnConnect.setText("Connect");
        btnConnect.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt) {
                btnConnectMouseClicked(evt);
            }
        });

        GroupLayout ConnectionPanelLayout = new GroupLayout(ConnectionPanel);
        ConnectionPanel.setLayout(ConnectionPanelLayout);
        ConnectionPanelLayout.setHorizontalGroup(
            ConnectionPanelLayout.createParallelGroup(Alignment.LEADING)
            .addGroup(ConnectionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ConnectionPanelLayout.createParallelGroup(Alignment.LEADING)
                    .addComponent(scrlSerialPorts, GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                    .addComponent(btnDetectSerial, GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                    .addComponent(btnConnect, GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE))
                .addContainerGap())
        );
        ConnectionPanelLayout.setVerticalGroup(
            ConnectionPanelLayout.createParallelGroup(Alignment.LEADING)
            .addGroup(ConnectionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnDetectSerial)
                .addPreferredGap(ComponentPlacement.RELATED)
                .addComponent(scrlSerialPorts, GroupLayout.PREFERRED_SIZE, 134, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(ComponentPlacement.RELATED)
                .addComponent(btnConnect)
                .addContainerGap(268, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Connection", ConnectionPanel);

        DisplayPanel.setBorder(BorderFactory.createEtchedBorder());
        DisplayPanel.setLayout(new GridLayout(12, 1));

        jLabel2.setText(" Background:");
        DisplayPanel.add(jLabel2);

        sldBackground.setPaintTicks(true);
        sldBackground.setValue(0);
        sldBackground.addChangeListener(new ChangeListener() {
            public void stateChanged(ChangeEvent evt) {
                sldBackgroundStateChanged(evt);
            }
        });
        DisplayPanel.add(sldBackground);

        chkPause.setText("Pause");
        chkPause.addChangeListener(new ChangeListener() {
            public void stateChanged(ChangeEvent evt) {
                chkPauseStateChanged(evt);
            }
        });
        DisplayPanel.add(chkPause);

        jLabel1.setText("Horizontal Scale:");
        DisplayPanel.add(jLabel1);

        sldZoom.setMaximum(256);
        sldZoom.setMinimum(1);
        sldZoom.setValue(256);
        sldZoom.addChangeListener(new ChangeListener() {
            public void stateChanged(ChangeEvent evt) {
                sldZoomStateChanged(evt);
            }
        });
        DisplayPanel.add(sldZoom);

        jLabel3.setText("Horizontal Pan:");
        DisplayPanel.add(jLabel3);

        sldPan.setMaximum(256);
        sldPan.setValue(0);
        sldPan.addChangeListener(new ChangeListener() {
            public void stateChanged(ChangeEvent evt) {
                sldPanStateChanged(evt);
            }
        });
        DisplayPanel.add(sldPan);

        jTabbedPane1.addTab("Display", DisplayPanel);

        CursorPanel.setLayout(new GridLayout(12, 0));

        chkCursors.setText("Enable Cursors");
        chkCursors.addChangeListener(new ChangeListener() {
            public void stateChanged(ChangeEvent evt) {
                chkCursorsStateChanged(evt);
            }
        });
        CursorPanel.add(chkCursors);

        jLabel4.setText("Horizontal Cursors:");
        CursorPanel.add(jLabel4);

        sldHC1.setMaximum(256);
        sldHC1.setValue(0);
        sldHC1.addChangeListener(new ChangeListener() {
            public void stateChanged(ChangeEvent evt) {
                sldHC1StateChanged(evt);
            }
        });
        CursorPanel.add(sldHC1);

        sldHC2.setMaximum(256);
        sldHC2.setValue(0);
        sldHC2.addChangeListener(new ChangeListener() {
            public void stateChanged(ChangeEvent evt) {
                sldHC2StateChanged(evt);
            }
        });
        CursorPanel.add(sldHC2);

        jLabel5.setText("Measurements:");
        CursorPanel.add(jLabel5);

        lblt1.setFont(new Font("Dialog", 0, 12)); // NOI18N
        lblt1.setText("t1 = ");
        CursorPanel.add(lblt1);

        lblt2.setFont(new Font("Dialog", 0, 12)); // NOI18N
        lblt2.setText("t2 = ");
        CursorPanel.add(lblt2);

        lbldt.setFont(new Font("Dialog", 0, 12)); // NOI18N
        lbldt.setText("dt = ");
        CursorPanel.add(lbldt);

        lblF.setFont(new Font("Dialog", 0, 12)); // NOI18N
        lblF.setText("1 / dt = ");
        CursorPanel.add(lblF);

        jTabbedPane1.addTab("Cursors", CursorPanel);

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jSlider6, GroupLayout.PREFERRED_SIZE, 0, GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(396, 396, 396)
                        .addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                    .addComponent(canvas, GroupLayout.DEFAULT_SIZE, 524, Short.MAX_VALUE))
                .addPreferredGap(ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, GroupLayout.PREFERRED_SIZE, 287, GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(430, 430, 430)
                        .addComponent(jSlider6, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(Alignment.LEADING)
                            .addComponent(jTabbedPane1, 0, 0, Short.MAX_VALUE)
                            .addComponent(canvas, GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE))))
                .addContainerGap())
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("Connection");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(MouseEvent evt) {//GEN-FIRST:event_formMouseClicked

            //rend.rotate = !rend.rotate;


    }//GEN-LAST:event_formMouseClicked

    private void canvasMouseDragged(MouseEvent evt) {//GEN-FIRST:event_canvasMouseDragged
        // TODO add your handling code here:
        if ((oldx == -1) || (oldy == -1))
        {
            oldx = evt.getX();
            oldy = evt.getY();
            return;
        }

        int dx = evt.getX() - oldx;
        int dy = oldy - evt.getY();


        oldx = evt.getX();
        oldy = evt.getY();

        rend.translate(dx, dy, 0);
    }//GEN-LAST:event_canvasMouseDragged

    private void canvasMouseReleased(MouseEvent evt) {//GEN-FIRST:event_canvasMouseReleased
        //Mouse drag ended
        oldx = -1;
        oldy = -1;
    }//GEN-LAST:event_canvasMouseReleased

    private void canvasMouseWheelMoved(MouseWheelEvent evt) {//GEN-FIRST:event_canvasMouseWheelMoved
        int dz =  -1 * evt.getWheelRotation();

        rend.translate(0, 0, dz);
    }//GEN-LAST:event_canvasMouseWheelMoved

    private void formWindowOpened(WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

    }//GEN-LAST:event_formWindowOpened

    private void formWindowActivated(WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        
    }//GEN-LAST:event_formWindowActivated

    private void sldBackgroundStateChanged(ChangeEvent evt) {//GEN-FIRST:event_sldBackgroundStateChanged
        // TODO add your handling code here:
        float c = (float) sldBackground.getValue() / (float) sldBackground.getMaximum();

        ScopeSettings.backr = c;
        ScopeSettings.backg = c;
        ScopeSettings.backb = c;
}//GEN-LAST:event_sldBackgroundStateChanged

    private void btnConnectMouseClicked(MouseEvent evt) {//GEN-FIRST:event_btnConnectMouseClicked
        String portname = (String)lstSerialPorts.getSelectedValue();

        System.out.println(portname);

        try {
            rend.arduino.connect(portname);
        } catch (Exception e) {
            System.err.println("Couldn't Connect: " + e);
        }

        rend.startTraceReader();

    }//GEN-LAST:event_btnConnectMouseClicked

    private void btnDetectSerialActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btnDetectSerialActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_btnDetectSerialActionPerformed

    private void btnDetectSerialMouseClicked(MouseEvent evt) {//GEN-FIRST:event_btnDetectSerialMouseClicked
        Vector<String> ports = rend.arduino.getPorts();

        lstSerialPorts.setListData(ports);
    }//GEN-LAST:event_btnDetectSerialMouseClicked

    private void chkPauseStateChanged(ChangeEvent evt) {//GEN-FIRST:event_chkPauseStateChanged
        ScopeSettings.paused = chkPause.isSelected();
    }//GEN-LAST:event_chkPauseStateChanged

    private void sldZoomStateChanged(ChangeEvent evt) {//GEN-FIRST:event_sldZoomStateChanged
        ScopeSettings.hZoom = sldZoom.getValue();
    }//GEN-LAST:event_sldZoomStateChanged

    private void sldPanStateChanged(ChangeEvent evt) {//GEN-FIRST:event_sldPanStateChanged
        ScopeSettings.hPan = sldPan.getValue();
    }//GEN-LAST:event_sldPanStateChanged

    private void chkCursorsStateChanged(ChangeEvent evt) {//GEN-FIRST:event_chkCursorsStateChanged
        ScopeSettings.enableCursors = chkCursors.isSelected();
        updateHLabels();
    }//GEN-LAST:event_chkCursorsStateChanged

    private void sldHC1StateChanged(ChangeEvent evt) {//GEN-FIRST:event_sldHC1StateChanged
        float x = sldHC1.getValue() / 128.0f - 1.0f;
        ScopeSettings.hc1 = x;
        updateHLabels();
    }//GEN-LAST:event_sldHC1StateChanged

    private void sldHC2StateChanged(ChangeEvent evt) {//GEN-FIRST:event_sldHC2StateChanged
        float x = sldHC2.getValue() / 128.0f - 1.0f;
        ScopeSettings.hc2 = x;
        updateHLabels();
    }//GEN-LAST:event_sldHC2StateChanged

    //update horizontal cursor (time) measurement labels
    private void updateHLabels()
    {
        if (ScopeSettings.enableCursors == false)
        {
            lblt1.setText("t1 = ");
            lblt2.setText("t2 = ");
            lbldt.setText("dt = ");
            lblF.setText("1 / dt = ");

            return;
        }


        //entire viewport represents a certain amount of time
        float windowTime = ScopeSettings.hZoom * ScopeSettings.samplePeriod;

        //Calculate the (relative) time of the cursors within the viewport
        float hc1 = sldHC1.getValue() / 256.0f;
        float hc2 = sldHC2.getValue() / 256.0f;

        //calculate measurements
        float t1 = hc1 * windowTime;
        float t2 = hc2 * windowTime;
        float dt = Math.abs(t2 - t1);
        float f = 1.0f / dt;


        //set labels
        lblt1.setText("t1 = " + (t1 * 1000.0f) + " ms");
        lblt2.setText("t2 = " + (t2 * 1000.0f) + " ms");
        lbldt.setText("dt = " + (dt * 1000.0f) + " ms");
        lblF.setText("1 / dt = " + f + " Hz");

    }

    /**
     * Called from within initComponents().
     * hint: to customize the generated code choose 'Customize Code' in the contextmenu
     * of the selected UI Component you wish to cutomize in design mode.
     * @return Returns customized GLCapabilities.
     */
    private GLCapabilities createGLCapabilites() {
        
        GLCapabilities capabilities = new GLCapabilities();
        capabilities.setHardwareAccelerated(true);

        // try to enable 2x anti aliasing - should be supported on most hardware
        capabilities.setNumSamples(2);
        capabilities.setSampleBuffers(true);
        
        return capabilities;
    }
    
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        // Run this in the AWT event thread to prevent deadlocks and race conditions
        EventQueue.invokeLater(new Runnable() {
            public void run() {

                // switch to system l&f for native font rendering etc.
                try{
                    UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                }catch(Exception ex) {
                    Logger.getLogger(getClass().getName()).log(Level.INFO, "can not enable system look and feel", ex);
                }

                GLScopeMac frame = new GLScopeMac();
                frame.setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JPanel ConnectionPanel;
    private JPanel CursorPanel;
    private JPanel DisplayPanel;
    private JButton btnConnect;
    private JButton btnDetectSerial;
    private GLCanvas canvas;
    private JCheckBox chkCursors;
    private JCheckBox chkPause;
    private JLabel jLabel1;
    private JLabel jLabel2;
    private JLabel jLabel3;
    private JLabel jLabel4;
    private JLabel jLabel5;
    private JPanel jPanel1;
    private JPanel jPanel4;
    private JSlider jSlider6;
    private JTabbedPane jTabbedPane1;
    private JLabel lblF;
    private JLabel lbldt;
    private JLabel lblt1;
    private JLabel lblt2;
    private JList lstSerialPorts;
    private JScrollPane scrlSerialPorts;
    private JSlider sldBackground;
    private JSlider sldHC1;
    private JSlider sldHC2;
    private JSlider sldPan;
    private JSlider sldZoom;
    // End of variables declaration//GEN-END:variables

}
